#ifndef WHATEVERGAME_SOURCE_ENGINE_NETWORK_EVENT_H_
#define WHATEVERGAME_SOURCE_ENGINE_NETWORK_EVENT_H_

enum class GameEventType{
  Default = 0
};

#endif //WHATEVERGAME_SOURCE_ENGINE_NETWORK_EVENT_H_
