//
// Created by roman on 23.04.24.
//

#ifndef WHATEVERGAME_SOURCE_MULTIPLAYER_WHATEVERSERVER_H_
#define WHATEVERGAME_SOURCE_MULTIPLAYER_WHATEVERSERVER_H_

class WhateverServer {

};

#endif //WHATEVERGAME_SOURCE_MULTIPLAYER_WHATEVERSERVER_H_
